### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by bvaughn** [comment]
Nice call @mohsen1 +1 from me

**Comment by mohsen1** [comment]
For some reason it's not kicking off builds. I'm giving some more time to it.

**Comment by bvaughn** [comment]
Cool beans. I haven't actually used Travis before with Github, although now that I think of it...I should have been ;)

**Comment by mchapman** [comment]
I have - you quite often get false negatives (ie it fails when it should
pass).  Which leaves your badges looking a bit sad. :(   Though come to
think of it I haven't had one for a couple of months, so maybe they have
gone away.

**Comment by mohsen1** [comment]
I use TravisCI in multiple projects. I do have Xvfb and Firefox launching during build process and I can say I've seen  less than 1% false negative. It all depends on the build process itself. 

For example take a look at build of Swagger Editor: 
https://travis-ci.org/swagger-api/swagger-editor

**Pull request merged**
